"""empty message

Revision ID: 2aff7c43d119
Revises: 44d4e22c1a62
Create Date: 2021-03-01 17:09:52.158623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2aff7c43d119'
down_revision = '44d4e22c1a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "Artist" ALTER COLUMN genres TYPE VARCHAR[] USING STRING_TO_ARRAY(genres, \',\')')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "Artist" ALTER COLUMN genres TYPE VARCHAR USING ARRAY_TO_STRING(genres, \',\')')
    # ### end Alembic commands ###
