"""empty message

Revision ID: 33358227468d
Revises: 6084628f575c
Create Date: 2021-02-15 16:37:42.678591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33358227468d'
down_revision = '6084628f575c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###

    op.execute('UPDATE "Venue" SET seeking_talent = False WHERE seeking_talent IS NULL;')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    op.drop_column('Venue', 'seeking_talent')
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###
