"""empty message

Revision ID: 44d4e22c1a62
Revises: f8c08df8446d
Create Date: 2021-03-01 16:35:44.958382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d4e22c1a62'
down_revision = 'f8c08df8446d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "Venue" ALTER COLUMN genres TYPE VARCHAR[] USING STRING_TO_ARRAY(genres, \',\')')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE "Venue" ALTER COLUMN genres TYPE VARCHAR USING ARRAY_TO_STRING(genres, \',\')')
    # ### end Alembic commands ###
