"""empty message

Revision ID: 4cd212dbe886
Revises: fcbd50c1a8e9
Create Date: 2021-02-20 18:00:22.775228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4cd212dbe886'
down_revision = 'fcbd50c1a8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.alter_column('Show', 'am',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('Show', 'day',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('Show', 'date')
    op.drop_column('Show', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('Show', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.alter_column('Show', 'day',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('Show', 'am',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
