"""empty message

Revision ID: 6084628f575c
Revises: 9b3b8cde9799
Create Date: 2021-02-12 16:11:18.315498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6084628f575c'
down_revision = '9b3b8cde9799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('am', sa.Boolean(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
