"""empty message

Revision ID: f8c08df8446d
Revises: 4cd212dbe886
Create Date: 2021-02-27 16:36:20.369821

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'f8c08df8446d'
down_revision = '4cd212dbe886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('listed_time', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('listed_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

    today_time_str = datetime.today().strftime(f'%Y-%m-%d %H:%M:%S')
    op.execute(f'UPDATE "Artist" SET listed_time = \' {today_time_str} \' WHERE listed_time IS NULL;')
    op.execute(f'UPDATE "Venue" SET listed_time = \' {today_time_str} \' WHERE listed_time IS NULL;')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'listed_time')
    op.drop_column('Artist', 'listed_time')
    # ### end Alembic commands ###
